version: 2
jobs:
  build:
    docker:
      - image: node:12.12

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run: npm test -- --coverage | grep Statements | awk '{print $3}'

      - run:
          name: post code coverage to seriesci
          command: |
            npm test -- --coverage | grep Statements | awk '{print $3}' | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data-urlencode value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/cra/coverage/combined

      - run:
          name: post bundle size to seriesci
          command: |
            npm run build
            du -sh build/ | awk '{print $1}' | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data-urlencode value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/cra/bundlesize/combined

      - run:
          name: post build time to seriesci
          command: |
            \time -f '%es' npm run build >/dev/null | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data-urlencode value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/cra/time/combined
