version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13-buster-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - run: npm test -- --coverage | grep Statements | awk '{print $3}'

      - run:
          name: lighthouse
          command: |
            cd build
            python3 -m http.server 5555 &
            npx lighthouse http://localhost:5555 --output json --output-path=./lighthouse.json --chrome-flags="--headless"

      - run:
          name: post code coverage to seriesci
          command: |
            npm test -- --coverage | grep Statements | awk '{print $3}' | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data-urlencode value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/cra/coverage/combined

      - run:
          name: post bundle size to seriesci
          command: |
            npm run build
            du -sh build/ | awk '{print $1}' | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data-urlencode value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/cra/bundlesize/combined

      - run:
          name: post build time to seriesci
          command: |
              apt-get update
              apt-get install bc
              start=$(date +%s.%N)
              npm run build
              duration=$(echo "$(date +%s.%N) - $start" | bc)
              echo "$duration s" | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data-urlencode value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/cra/time/combined

      - run:
          name: post number of dependencies to seriesci
          command: |
              (npm ls --depth=0 --prod --parseable --silent || true) | grep node_modules | wc -l | xargs -I {} curl \
              --header "Authorization: Token ${TOKEN}" \
              --data-urlencode value="{}" \
              --data sha="${CIRCLE_SHA1}" \
              https://seriesci.com/api/repos/seriesci/cra/dependencies/combined
